# Generated by Django 4.2.3 on 2023-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='categoryType',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Статья', max_length=10),
        ),
    ]
