# Generated by Django 4.2.3 on 2023-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='board_videos/'),
        ),
    ]
