# Generated by Django 4.2.3 on 2023-10-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funapp', '0005_alter_board_image_alter_board_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='board_videos/'),
        ),
    ]
