# Generated by Django 4.2.3 on 2023-08-28 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0002_alter_news_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynews',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='categories', through='newapp.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
