# Generated by Django 4.2.3 on 2023-09-27 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynews',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='newapp.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
