# Generated by Django 4.2.3 on 2023-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_categorynews_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
