# Generated by Django 4.2.3 on 2023-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_news_description_en_us_news_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoryType_en_us',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Статья', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='categoryType_ru',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Статья', max_length=10, null=True),
        ),
    ]
