# Generated by Django 4.2.3 on 2023-09-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_news_categorytype_en_us_news_categorytype_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='categoryType_en_us',
        ),
        migrations.RemoveField(
            model_name='news',
            name='categoryType_ru',
        ),
    ]
